### PR TITLE
Fixed typo in NfcForegroundDispatchFilter.yml

### PR DESCRIPTION
**Pull request by jawa9000**
Fixed typo in the type attribute of techLists property.

### CODE REVIEW

**Comment by jawa9000** [comment]
@hansemannn, it shouldn't look this this, right:
Array<Array<String>>

**Comment by hansemannn** [comment]
Well, technically that is correct, since it is an array of arrays. Probably our docs-script needs to be updated to handle this properly.

**Comment by jawa9000** [comment]
Would it be ok, for now, to just set the type to array and publish it since the current docs say 

> String[][]

**Comment by hansemannn** [comment]
The current docs are correct then. `[][]` means nested array. How come it was detected as a bug?

**Comment by jawa9000** [comment]
I'm not sure why the doc pub scripts are reporting this (and a few others) as problems. I'm still investigating the issue.

**Pull request closed without merging**
